<?xml version="1.0"?>
<robot>

  <property name="ground_clearance" value="0.0740" />
  <property name="level1_clearance" value="0.18" />
  <property name="level2_clearance" value="0.24" />
  <property name="level3_clearance" value="0.305" />
  <property name="wheel_offset_y" value="0.116" />
  <property name="wheel_length" value="0.02032" />
  <property name="wheel_radius" value="0.06191" />
  <property name="swivel_length" value="0.019" />
  <property name="swivel_radius" value="0.025" />
  <property name="base_radius" value="0.15" />
  <property name="base_collision_radius" value="0.20" />
  <property name="base_length" value="0.006" />
  <property name="sonar_clearance" value="${ground_clearance-0.02}" />
  <property name="sonar_angle" value="0.6" />


  <!-- define a rotating wheel -->
  <macro name="frobo_wheel" params="suffix parent reflect color">
    <joint name="${parent}_${suffix}_wheel_joint" type="continuous">
      <axis xyz="0 0 1" />
      <limit effort="100" velocity="100"/>
      <safety_controller k_velocity="10" />
      <origin xyz="0 ${reflect*wheel_offset_y} ${wheel_radius}" rpy="${reflect*1.57} 0 0" />
      <parent link="${parent}_link"/>
      <child link="${parent}_${suffix}_wheel_link"/>
    </joint>
    <link name="${parent}_${suffix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <material name="${color}" />
      </visual>
    </link>
  </macro>

  <!-- define a sonar -->
  <macro name="frobo_sonar" params="suffix parent offset_x offset_y angle color">
    <joint name="${parent}_${suffix}_sonar_joint" type="fixed">
      <origin xyz="${offset_x} ${offset_y} ${sonar_clearance}" rpy="0 0 ${angle}" />
      <parent link="${parent}_link"/>
      <child link="${parent}_${suffix}_sonar_link"/>
    </joint>
    <link name="${parent}_${suffix}_sonar_link">
      <visual>
        <origin xyz="0 0 0" rpy="-1.57 0 1.57" />
        <geometry>
          <mesh filename="package://frobo_description/meshes/sonar.stl"  /> 
        </geometry>
        <material name="${color}" />
      </visual>
    </link>
  </macro>

  <!-- The xacro macro frobo_base contains: base and wheels -->
  <macro name="frobo_base" params="name color">
    <link name="${name}_link">
      <visual>
        <origin xyz="0 0 ${ground_clearance}" rpy="0 0 0" />
        <geometry>
          <!-- <mesh filename="package://frobo_description/meshes/base.stl"  /> -->
	  <cylinder radius="${base_radius}" length="${base_length}"/>
        </geometry>
        <material name="${color}" />
      </visual>
      <visual>
        <origin xyz="0 0 ${level1_clearance}" rpy="0 0 0" />
        <geometry>
	  <cylinder radius="${base_radius}" length="${base_length}"/>
        </geometry>
        <material name="${color}" />
      </visual>
      <visual>
        <origin xyz="0 0 ${level2_clearance}" rpy="0 0 0" />
        <geometry>
	  <cylinder radius="${base_radius}" length="${base_length}"/>
        </geometry>
        <material name="${color}" />
      </visual>
      <visual>
        <origin xyz="0 0 ${level3_clearance}" rpy="0 0 0" />
        <geometry>
	  <cylinder radius="${base_radius}" length="${base_length}"/>
        </geometry>
        <material name="${color}" />
      </visual>
      <!-- fixed wheels, without tf transform, just for visualization -->
      <visual>
        <origin xyz="0 ${1*wheel_offset_y} ${wheel_radius}" rpy="1.57 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <material name="Orange" />
      </visual>
      <visual>
        <origin xyz="0 ${-1*wheel_offset_y} ${wheel_radius}" rpy="1.57 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <material name="Orange" />
      </visual>
      <!-- fixed swivel, without tf transform, just for visualization -->
      <!--
      <visual>
        <origin xyz="-${wheel_offset_y} 0 ${swivel_radius}" rpy="1.57 0 0" />
        <geometry>
          <cylinder radius="${swivel_radius}" length="${swivel_length}"/>
        </geometry>
        <material name="Grey" />
      </visual> 
      -->
      <collision>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${base_collision_radius}" length="${wheel_radius*2}" />
        </geometry>
      </collision>
    </link>
  
    <!-- drive wheels -->
    <!--<frobo_wheel parent="${name}" suffix="l" reflect="1" color="Orange"/>
    <frobo_wheel parent="${name}" suffix="r" reflect="-1" color="Orange"/>-->

    <!-- sonars -->
    <frobo_sonar parent="${name}" offset_x="0.115" offset_y="-0.055" angle="-${sonar_angle}" suffix="fr" color="Blue"/>
    <frobo_sonar parent="${name}" offset_x="0.125" offset_y="0" angle="0" suffix="fc" color="Blue"/>
    <frobo_sonar parent="${name}" offset_x="0.115" offset_y="0.055" angle="${sonar_angle}" suffix="fl" color="Blue"/>
	
  </macro>

</robot>
