<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:property name="kinect_size_x" value="0.07271" />
    <xacro:property name="kinect_size_y" value="0.27794" />
    <xacro:property name="kinect_size_z" value="0.070" />
    <xacro:property name="kinect_offset_z" value="0.035" />
    <xacro:property name="kinect_frame_offset_z" value="0.015" />
    <xacro:property name="kinect_frame_offset_y" value="0.0125" />
    <xacro:property name="camera_mesh_scale" value="1.0" />
  
    <xacro:macro name="kinect_camera_model" params="name parent *origin">
      <joint name="${name}_joint" type="fixed">
        <xacro:insert_block name="origin" />
        <parent link="${parent}"/>
        <child link="${name}_link"/>
      </joint>
      
      <link name="${name}_link">
        <inertial_sphere mass="0.01" diameter="0.07" />
        <visual>
          <origin xyz="0 0 ${kinect_offset_z}" rpy="0 0 ${PI/2}" />
          <geometry>
<!--
            <mesh filename="package://frobo_description/meshes/kinect_camera_simple.dae"/>
-->
            <mesh filename="package://frobo_description/meshes/kinect.dae" scale="${camera_mesh_scale} ${camera_mesh_scale} ${camera_mesh_scale}"/>
          </geometry>
        </visual>
        <collision>
          <origin xyz="0 0 ${kinect_offset_z}" rpy="0 0 0" />
          <geometry>
              <box size="${kinect_size_x} ${kinect_size_y} ${kinect_size_z}"/>
           </geometry>
        </collision>
      </link>

      <joint name="${name}_depth_joint" type="fixed">
        <origin xyz="0.0 ${kinect_frame_offset_y} ${kinect_offset_z+kinect_frame_offset_z}" rpy="0 0 0" />
        <parent link="${name}_link" />
        <child link="${name}_depth_frame"/>
      </joint>

      <link name="${name}_depth_frame">
         <inertial>
             <mass value="0.000001" />
             <origin xyz="0 0 0" />
             <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                iyy="0.0001" iyz="0.0"
                izz="0.0001" />
         </inertial>
      </link>

      <joint name="${name}_depth_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-PI/2} 0.0 ${-PI/2}" />
        <parent link="${name}_depth_frame" />
        <child link="${name}_depth_optical_frame"/>
      </joint>

      <link name="${name}_depth_optical_frame">
         <inertial>
            <mass value="0.000001" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001" />
         </inertial>
      </link>

      <joint name="${name}_rgb_joint" type="fixed">
        <origin xyz="0.0 -${kinect_frame_offset_y} ${kinect_offset_z+kinect_frame_offset_z}" rpy="0 0 0" />
        <parent link="${name}_link" />
        <child link="${name}_rgb_frame"/>
      </joint>

      <link name="${name}_rgb_frame">
        <inertial>
         <mass value="0.000001" />
         <origin xyz="0 0 0" />
         <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
            iyy="0.0001" iyz="0.0"
            izz="0.0001" />
         </inertial>
      </link>

      <joint name="${name}_rgb_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-PI/2} 0.0 ${-PI/2}" />
        <parent link="${name}_rgb_frame" />
        <child link="${name}_rgb_optical_frame"/>
      </joint>

      <link name="${name}_rgb_optical_frame">
        <inertial>
            <mass value="0.000001" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001" />
         </inertial>
      </link>
    </xacro:macro>

    <xacro:macro name="kinect_camera" params="name parent *origin">
      <xacro:kinect_camera_model name="${name}" parent="${parent}">
        <xacro:insert_block name="origin" />
      </xacro:kinect_camera_model>
    </xacro:macro>
</robot>
  
