<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="lidar_box_size_x" value="0.124" />
  <xacro:property name="lidar_box_size_y" value="0.105" />
  <xacro:property name="lidar_box_size_z" value="0.048" />
  <xacro:property name="lidar_radius" value="0.038" />
  <!-- offset relative to box - how much it sticks out on top -->
  <xacro:property name="lidar_offset_z" value="0.01" />
  

  <!-- define a lidar -->
  <xacro:macro name="lidar" params="name parent *origin">
    <joint name="${name}_bottom_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_bottom"/>
    </joint>
    
    <link name="${name}_bottom">
       <visual>
        <origin xyz="0 0 ${lidar_box_size_z/2}" rpy="0 0 0" />
        <geometry>
          <box size="${lidar_box_size_x} ${lidar_box_size_y} ${lidar_box_size_z}"/>
        </geometry>
        <material name="Black" /> 
      </visual>
      <collision>
        <origin xyz="0 0 ${lidar_box_size_z/2}" rpy="0 0 0" />
        <geometry>
           <box size="${lidar_box_size_x} ${lidar_box_size_y} ${lidar_box_size_z}"/>
        </geometry>
      </collision>
      <inertial>
       <mass value="0.1" />
         <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                   iyy="0.001" iyz="0.0"
                   izz="0.001" />                     
      </inertial>
    </link>
    
    <link name="${name}_link">
	 <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
		<geometry>
          <cylinder radius="${lidar_radius}" length="${lidar_offset_z}"/>
        </geometry>
        <material name="Red"/>          
     </visual>
     <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
		 <geometry>
          <cylinder radius="${lidar_radius}" length="${lidar_offset_z}"/>
         </geometry>
       </collision>
	 <inertial>
       <mass value="0.1" />
         <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                   iyy="0.001" iyz="0.0"
                   izz="0.001" />                     
      </inertial>
   </link>
   
   <joint name="${name}_joint" type="fixed">
     <parent link="${name}_bottom"/>
     <child link="${name}_link" />
     <origin xyz="0 0 ${lidar_box_size_z+lidar_offset_z/2}" rpy="0 0 0" />
   </joint>
    
  </xacro:macro>

</robot>
