port: /dev/ttyUSB0
baud: 115200
rate: 20
sync_write: True
sync_read: True
read_rate: 20
write_rate: 20

controllers: {
   base_controller: {type: diff_controller, base_frame_id: base_footprint, base_width: 0.30, ticks_meter: 6533, Kp: 12, Kd: 12, Ki: 0, Ko: 50, accel_limit: 1.0 }
}
