<?xml version="1.0"?>
<robot>

  <property name="ground_clearance" value="0.0740" />
  <!-- simplified box collision geometry for base -->
  <property name="wheel_offset_y" value="0.116" />
  <property name="wheel_length" value="0.02032" />
  <property name="wheel_radius" value="0.06191" />
  <property name="swivel_length" value="0.019" />
  <property name="swivel_radius" value="0.025" />
  <property name="swivel_offset_z" value="0.004" />
  <property name="base_radius" value="0.15" />
  <property name="base_collision_radius" value="0.20" />
  <property name="base_length" value="0.006" />

  <!-- define a wheel -->
  <macro name="frobo_wheel" params="suffix parent reflect color">
    <joint name="${parent}_${suffix}_wheel_joint" type="continuous">
      <axis xyz="0 0 1" />
      <limit effort="100" velocity="100"/>
      <safety_controller k_velocity="10" />
      <origin xyz="0 ${reflect*wheel_offset_y} ${wheel_radius}" rpy="${reflect*1.57} 0 0" />
      <parent link="${parent}_link"/>
      <child link="${parent}_${suffix}_wheel_link"/>
    </joint>
    <link name="${parent}_${suffix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <material name="${color}" />
      </visual>
    </link>
  </macro>
  
  <!-- The xacro macro frobo_base contains: base and wheels -->
  <macro name="frobo_base" params="name color">
    <link name="${name}_link">
      <visual>
        <origin xyz="0 0 ${ground_clearance}" rpy="0 0 0" />
        <geometry>
          <!-- <mesh filename="package://frobo_defs/meshes/base.stl"  /> -->
	  <cylinder radius="${base_radius}" length="${base_length}"/>
        </geometry>
        <material name="Black" />
      </visual>
      <collision>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${base_collision_radius}" length="${wheel_radius*2}" />
        </geometry>
      </collision>
    </link>
  
    <!-- drive wheels -->
    <frobo_wheel parent="${name}" suffix="l" reflect="1" color="${color}"/>
    <frobo_wheel parent="${name}" suffix="r" reflect="-1" color="${color}"/>
	
	<!-- sonars -->
	
	<!-- Swivel -->
	<link name="swivel">
		<inertial>
			<mass value="0"/>	
			<origin xyz="0 0 0"/>
			<inertia ixx="1" ixy="0" ixz="0"
				 iyy="1" iyz="0" izz="1"/>
  	 	</inertial>
	<visual name="base_visual">
		<origin xyz="0 0 0.045" rpy="0 0 0"/>
		<geometry name="pioneer_geom">
			<mesh filename="package://frobo_defs/meshes/swivel.stl"/>
		</geometry>
		<material name="swivel">
			<color rgba="0.5 0.5 0.5 1"/>
		</material>
	</visual>
	<collision>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<box size="0 0 0"/>
		</geometry>
	</collision>
	</link>

 	<joint name="base_swivel_joint" type="continuous">
		<origin xyz="-${wheel_offset_y} 0 -${swivel_offset_z}" rpy="0 0 0"/>
		<axis xyz="0 0 1" />
		<anchor xyz="0 0 0" />
		<limit effort="100" velocity="100" />
		<joint_properties damping="0.0" friction="0.0" />
		<parent link="base_link"/>
		<child link="swivel"/>
	</joint>

<!-- Center Wheel + Hubcap -->
	<link name="center_hubcap">
		<inertial>
			<mass value="0"/>	
			<origin xyz="0 0 0"/>
			<inertia ixx="1" ixy="0" ixz="0"
				 iyy="1" iyz="0" izz="1"/>
  	 	</inertial>
	<visual name="base_visual">
		<origin xyz="0 0 0.045" rpy="0 0 0"/>
		<geometry name="pioneer_geom">
			<mesh filename="package://frobo_defs/meshes/center_hubcap.stl"/>
		</geometry>
		<material name="swivel">
			<color rgba="0.5 0.5 0.5 1"/>
		</material>
	</visual>
	<collision>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<box size="0 0 0"/>
		</geometry>
	</collision>
	</link>
	
	<joint name="swivel_hubcap_joint" type="continuous">
		<origin xyz="-0.026 0 -0.016" rpy="0 0 0"/>
		<axis xyz="0 1 0" />
		<anchor xyz="0 0 0" />
		<limit effort="100" velocity="100" />
		<joint_properties damping="0.0" friction="0.0" />
		<parent link="swivel"/>
		<child link="center_hubcap"/>
	</joint>

	<link name="center_wheel">
		<inertial>
			<mass value="0"/>	
			<origin xyz="0 0 0"/>
			<inertia ixx="1" ixy="0" ixz="0"
				 iyy="1" iyz="0" izz="1"/>
  	 	</inertial>
	<visual name="base_visual">
		<origin xyz="0 0 0.045" rpy="1.57 0 0"/>
		<geometry name="pioneer_geom">
			<!-- <mesh filename="package://frobo_defs/meshes/center_wheel.stl"/> -->
			<cylinder radius="${swivel_radius}" length="${swivel_length}"/>
		</geometry>
		<material name="WheelBlack">
			<color rgba="0.117 0.117 0.117 1"/>
		</material>
	</visual>
	<collision>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<box size="0 0 0"/>
		</geometry>
	</collision>
	</link>

	<joint name="center_wheel_joint" type="fixed">
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<parent link="center_hubcap"/>
		<child link="center_wheel"/>
	</joint>

  </macro>

</robot>
