obstacle_range: 0.2    #only add obstacles within 1m
raytrace_range: 1.0    #clear obstacles out over a distance of 2m
robot_radius: 0.20
inflation_radius: 0.20
max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: sonarCenter sonarLeft sonarRight
sonarCenter: {sensor_frame: /base_fc_sonar_link, data_type: PointCloud, topic: /arduino/sensor/sonar_front_center, marking: true, clearing: true, expected_update_rate: 2, observation_persistence: 0.0, obstacle_range: 0.2, raytrace_range: 1.0}
sonarLeft: {sensor_frame: /base_fl_sonar_link, data_type: PointCloud, topic: /arduino/sensor/sonar_front_left, marking: true, clearing: true, expected_update_rate: 2, observation_persistence: 0.0, obstacle_range: 0.2, raytrace_range: 1.0}
sonarRight: {sensor_frame: /base_fr_sonar_link, data_type: PointCloud, topic: /arduino/sensor/sonar_front_right, marking: true, clearing: true, expected_update_rate: 2, observation_persistence: 0.0, obstacle_range: 0.2, raytrace_range: 1.0}
