controller_frequency: 3.0
recovery_behavior_enabled: true
clearing_rotation_allowed: true

TrajectoryPlannerROS:
   max_vel_x: 0.15
   min_vel_x: 0.06
   max_rotational_vel: 1.0
   min_in_place_vel_theta: 0.6
   escape_vel: -0.1
   acc_lim_x: 1.0
   acc_lim_y: 0.0
   acc_lim_th: 1.0

   holonomic_robot: false
   yaw_goal_tolerance: 6.28 # 360 degrees
   xy_goal_tolerance: 0.25  # 25 cm
   latch_xy_goal_tolerance: false
   pdist_scale: 0.6
   gdist_scale: 0.8
   meter_scoring: true   #Whether the gdist_scale and pdist_scale parameters should assume that goal_distance and path_distance are expressed in units of meters or cells. Cells are assumed by default. CHANGED

   heading_lookahead: 0.625
   heading_scoring: false   #Whether to score based on the robot's heading to the path or its distance from the path
   heading_scoring_timestep: 0.8
   occdist_scale: 0.01   #The weighting for how much the controller should attempt to avoid obstacles - CHANGED from 0.1
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: false
   prune_plan: true

   sim_time: 3.0  #The amount of time to forward-simulate trajectories in seconds - CHANGED from 1.0 - sim_time*min_accel should be < min_tolerance*2!!
   sim_granularity: 0.1
   angular_sim_granularity: 0.1
   vx_samples: 8
   vtheta_samples: 20
   dwa: true  
   simple_attractor: false
